### PR TITLE
Allow TS story file extension

### PR DESCRIPTION
**Pull request by jinlee93**
With CSF 3.0 format, story files may not necessary use JSX lang and hence may be a TS file instead.
Updates rule `no-components-without-story` to allow TS file extension for stories.

### CODE REVIEW

**Review by ahuth — APPROVED** [review]
Nice, LGTM

**Review by dierat — APPROVED** [review]
Nice!

**Review by booc0mtaco — APPROVED** [review]
++

**Comment by ahuth** [comment]
After merging, follow https://github.com/chanzuckerberg/frontend-libs/wiki/Publishing-releases to publish.

FYI, the order of the steps there is important (because of the jankiness of the publishing process I concocted)

**Pull request merged**
