### PR TITLE
Remove Link from remix-utils

### PR DESCRIPTION
**Pull request by ahuth**
This PR removes the Link component from remix-utils.

I've not been able to get it to work right with edu-stack + EDS v12 (which ships CJS modules):
- Tree shaking doesn't seem to work in the browser build. Probably because [esbuild only tree shakes ESM](https://esbuild.github.io/api/#tree-shaking).
- There's a runtime error because `clsx`'s default export isn't a function or something. Perplexing.

Some thoughts:
- We could debug this some more, but I'm thinking it's not worth a lot more time.
- esbuild is conservative in its tree shaking. It readily bails out.
- Accessing EDS through an intermediate package (like remix-utils) seems likely to cause grief right now (for both module interop issues and tree shaking).
- For now we'll bake the Link component into edu-stack.
- Not ideal, since all Remix apps will duplicate it. But sometimes we have to do the least worst thing.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM

> * For now we'll bake the Link component into edu-stack.
> * Not ideal, since all Remix apps will duplicate it. But sometimes we have to do the least worst thing.

I know we've already discussed this a few times but maybe "adding an `as` prop to the `<Link />` component" has more favor now? Re: https://github.com/chanzuckerberg/edu-ps-goal-setting-test/pull/15#discussion_r1083163438

**Review by jinlee93 — APPROVED** [review]

**Comment by jeremiah-clothier** [comment]
Reviving this thread https://github.com/chanzuckerberg/edu-ps-goal-setting-test/pull/15#discussion_r1083163438 surrounding adding as `as` prop to the `<Link />` component.

@booc0mtaco, in regards to your last comment, do we have a firmer recommendation for this approach?

**Comment by booc0mtaco** [comment]
> Reviving this thread [chanzuckerberg/edu-ps-goal-setting-test#15 (comment)](https://github.com/chanzuckerberg/edu-ps-goal-setting-test/pull/15#discussion_r1083163438) surrounding adding as `as` prop to the `<Link />` component.
> 
> @booc0mtaco, in regards to your last comment, do we have a firmer recommendation for this approach?

This is a little tricky as we have seen. Maybe it's worth investigating this `as` prop approach again. I think part of the problem is that both `Link` and `Button` are already using something like this to re-use `ClickableStyle`. We have a ticket to simplify that, which could position us to better solve this use case:

https://czi-tech.atlassian.net/browse/EFI-994

Let's take some time this week to check requirements and add a few more details to that ticket

**Comment by andremalan** [comment]
*Cough cough* CSS-based EDS 😅

**Pull request merged**
